version: '3'
services:
        mica:
                #build: ../docker-mica
                image: obiba/mica:snapshot
                ports:
                        - "8872:8082"
                links:
                        - mongo
                environment:
                        - JAVA_OPTS=-Xmx2G
                        - MICA_ADMINISTRATOR_PASSWORD=password
                        - MICA_ANONYMOUS_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - AGATE_HOST=agate
                        - AGATE_PORT=8444
                volumes:
                        - /tmp/test-mica:/srv
        mongo:
                image: mongo:4.2
        agate:
                #build: ../docker-agate
                image: obiba/agate:latest
                ports:
                        - "8871:8081"
                links:
                        - mongo
                environment:
                        - AGATE_ADMINISTRATOR_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - RECAPTCHA_SITE_KEY=6LdANggTAAAAAEBWCuEL-YkFd3ehtzlg4CzQpn3e
                        - RECAPTCHA_SECRET_KEY=6LdANggTAAAAAMds-qrsU6P-STY7GZ3nRgQEuWZE
                volumes:
                        - /tmp/test-agate:/srv
